version: "3"

x-logging: &default-logging
  driver: "loki"
  options:
    loki-url: http://localhost:3100/loki/api/v1/push


services:
  web:
    logging: *default-logging
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - 3000
    volumes:
      - ./web:/app:rw
    tty: true
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - postgres
    labels:
      traefik.http.routers.dtts-web.rule: PathPrefix(`/`)
      traefik.http.services.dtts-web.loadbalancer.server.port: 3000
    networks:
      - traefik

  api:
    logging: *default-logging
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - 5000
    tty: true
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - postgres
      - redis
      - influxdb
    labels:
      traefik.http.routers.dtts-api.rule: PathPrefix(`/api`)
      traefik.http.routers.dtts-api.middlewares: dtts-api-stripprefix
      traefik.http.middlewares.dtts-api-stripprefix.stripprefix.prefixes: /api
      traefik.http.services.dtts-api.loadbalancer.server.port: 5000
    networks:
      - postgres
      - redis
      - influxdb
      - traefik

  bot:
    logging: *default-logging
    build:
      context: ./bot
      dockerfile: Dockerfile.prod
    entrypoint: bash
    tty: true
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - postgres
      - redis
      - influxdb
    networks:
      - postgres
      - redis
      - influxdb

  postgres:
    logging: *default-logging
    image: postgres:15.1
    container_name: postgres
    restart: always
    ports:
      - 12484:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    env_file:
      - .env.prod
    networks:
      - postgres

  redis:
    logging: *default-logging
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - 6379
    volumes:
      - ./.data/redis:/data
    env_file:
      - .env.prod
    networks:
      - redis

  traefik:
    logging: *default-logging
    image: traefik:v2.5.3
    restart: always
    ports:
      - 13080:80
      - 13443:443
      - 18080:8080
    depends_on:
      - web
      - api
    volumes:
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik

  influxdb:
    logging: *default-logging
    image: influxdb:2.6
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./.data/influxdb2:/var/lib/influxdb2
      - ./.data/config/influxdb2:/etc/influxdb2
    env_file:
      - .env.prod
    networks:
      - influxdb
      - grafana

  grafana:
    logging: *default-logging
    image: grafana/grafana:9.3.6
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./.data/grafana:/var/lib/grafana
    env_file:
      - .env.prod
    depends_on:
      - influxdb
      - loki
    networks:
      - grafana

  telegraf:
    logging: *default-logging
    image: telegraf:1.25.0
    container_name: telegraf
    restart: always
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/rootfs/proc:ro
      - /sys:/rootfs/sys:ro
      - /etc:/rootfs/etc:ro
    env_file:
      - .env.prod
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    depends_on:
      - influxdb
    networks:
      - influxdb

  loki:
    image: grafana/loki:2.7.3
    container_name: loki
    restart: always
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana

networks:
  postgres:
  redis:
  influxdb:
  grafana:
  traefik:
